import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'business-os-security-v2-'));
process.env.BUSINESS_OS_DATA_DIR=temp;
const {evaluateSecurityRequest,getSecurityIntegrity}=await import('../server/security/securityKernel.ts');
const {createProvenanceRecord,verifyProvenanceRecord}=await import('../server/security/provenance.ts');
const denied=evaluateSecurityRequest({actionId:'deny',title:'Denied',targetSystem:'Data',authorizedBy:'',parameters:{},humanApproval:true,requiresApproval:true,riskLevel:'low'});
assert.equal(denied.decision,'DENY');
const approval=evaluateSecurityRequest({actionId:'approval',title:'Approval',targetSystem:'Data',authorizedBy:'operator',parameters:{},humanApproval:false,requiresApproval:true,riskLevel:'medium'});
assert.equal(approval.decision,'REQUIRE_HUMAN');
const allowed=evaluateSecurityRequest({actionId:'allowed',title:'Allowed',targetSystem:'Data',authorizedBy:'operator',parameters:{},humanApproval:true,requiresApproval:true,riskLevel:'low',agentId:'agent-1'});
assert.equal(allowed.allowed,true);
assert.equal(getSecurityIntegrity().valid,true);
const record=createProvenanceRecord({subject:'vault/object-1',payload:{hello:'world'},source:'offline-vault',authorizedBy:'operator'});
assert.equal(verifyProvenanceRecord(record,{hello:'world'}).valid,true);
assert.equal(verifyProvenanceRecord(record,{hello:'tampered'}).valid,false);
console.log('security-runtime-v2: PASS');